/* Grammar Focus: UN contenido KC por actividad, trabajado con distintos formatos
   de pregunta (completar, elegir la oración correcta, transformar, doble hueco,
   definición). Cortas a propósito: 6 preguntas (hasta 15 si el tema lo pide), 3–4 alternativas.

   Por ahora, los cursos del semestre: Básico II, Elemental I, Intermedio I e
   Intermedio Intensivo. El intensivo reutiliza los de Intermedio I en su EA1
   (mismos KC) y suma los suyos propios. */

import { mc } from './logic.js'

const focus = (topic, ...questions) => ({ topic, questions })

/* ───────────── Básico II ───────────── */

const BASICO2_EA1 = [
  focus('Word order in questions',
    mc('Choose the correct question.', 'What do you do on Sundays?', 'What you do on Sundays?', 'What do on Sundays you?', 'What does you do on Sundays?'),
    mc('Where ___ your parents live?', 'do', 'does', 'are', 'is'),
    mc('What time ___ Sara get up?', 'does', 'do', 'is', 'are'),
    mc('Choose the correct question.', 'Do you like pizza?', 'Like you pizza?', 'Does you like pizza?', 'Are you like pizza?'),
    mc('___ he ___ in an office?', 'Does / work', 'Do / works', 'Does / works', 'Is / work'),
    mc('Choose the correct question.', 'How often do you go to the movies?', 'How often you go to the movies?', 'How often go you to the movies?', 'How do often you go to the movies?'),
  ),
  focus('Object pronouns',
    mc('I love this song. Listen to ___!', 'it', 'him', 'them', 'its'),
    mc('My parents are great. I call ___ every day.', 'them', 'they', 'their', 'us'),
    mc('Where’s Tom? I need to talk to ___.', 'him', 'he', 'his', 'her'),
    mc('Can you help ___? I can’t open the door.', 'me', 'I', 'my', 'mine'),
    mc('We’re here! Can you see ___?', 'us', 'we', 'our', 'them'),
    mc('Choose the correct sentence.', 'She loves him.', 'She loves he.', 'Her loves him.', 'She loves his.'),
  ),
  focus('Can / can’t',
    mc('I ___ swim. I never learned.', 'can’t', 'don’t', 'not can', 'am not'),
    mc('___ I open the window? It’s hot.', 'Can', 'Am', 'Does', 'Do'),
    mc('She can ___ very well.', 'dance', 'dances', 'dancing', 'to dance'),
    mc('Choose the correct question.', 'Can you help me?', 'Do you can help me?', 'Can you to help me?', 'Can you helps me?'),
    mc('You ___ use your phone in the exam. It’s not allowed.', 'can’t', 'don’t can', 'not can', 'aren’t'),
    mc('Can he drive? – No, he ___.', 'can’t', 'doesn’t', 'isn’t', 'not'),
  ),
  focus('Like / love / hate + -ing',
    mc('I hate ___ early.', 'getting up', 'get up', 'gets up', 'to getting up'),
    mc('Do you like ___?', 'cooking', 'cook', 'cooks', 'to cooking'),
    mc('She loves ___ to music.', 'listening', 'listen', 'listens', 'listened'),
    mc('He doesn’t like ___ TV.', 'watching', 'watch', 'watches', 'to watching'),
    mc('run → -ing', 'running', 'runing', 'runeing', 'runs'),
    mc('dance → -ing', 'dancing', 'danceing', 'dancng', 'dances'),
  ),
  focus('Present continuous or simple?',
    mc('Be quiet! The baby ___.', 'is sleeping', 'sleeps', 'sleep', 'sleeping'),
    mc('I ___ coffee every morning.', 'drink', 'am drinking', 'drinking', 'drinks'),
    mc('What ___ you doing now?', 'are', 'do', 'is', 'does'),
    mc('She ___ TV right now.', 'is watching', 'watches', 'watch', 'watching'),
    mc('He usually ___ the bus, but today he ___.', 'takes / is walking', 'is taking / walks', 'takes / walks', 'is taking / is walking'),
    mc('Choose the correct sentence.', 'They aren’t working today.', 'They don’t working today.', 'They not working today.', 'They aren’t work today.'),
  ),
]

const BASICO2_EA2 = [
  focus('There is / there are',
    mc('There ___ a sofa in the living room.', 'is', 'are', 'be', 'has'),
    mc('There ___ three chairs in the kitchen.', 'are', 'is', 'has', 'have'),
    mc('___ there any towels in the bathroom?', 'Are', 'Is', 'Has', 'Do'),
    mc('There ___ a TV in my room. I don’t have one.', 'isn’t', 'aren’t', 'not', 'don’t'),
    mc('Choose the correct question.', 'Is there a bank near here?', 'Is a bank there near here?', 'Are there a bank near here?', 'Has there a bank near here?'),
    mc('Are there two beds? – Yes, there ___.', 'are', 'is', 'have', 'do'),
  ),
  focus('Simple past: was / were',
    mc('I ___ at home last night.', 'was', 'were', 'am', 'did'),
    mc('The children ___ tired after the trip.', 'were', 'was', 'are', 'did'),
    mc('___ you at the party on Saturday?', 'Were', 'Was', 'Did', 'Are'),
    mc('She ___ at work yesterday. She was sick.', 'wasn’t', 'weren’t', 'didn’t', 'isn’t'),
    mc('Where ___ Tom born?', 'was', 'were', 'did', 'is'),
    mc('Were they happy? – Yes, they ___.', 'were', 'was', 'did', 'are'),
  ),
  focus('Simple past: regular verbs',
    mc('watch → past simple', 'watched', 'watchd', 'watcht', 'watches'),
    mc('stop → past simple', 'stopped', 'stoped', 'stopt', 'stops'),
    mc('live → past simple', 'lived', 'liveed', 'livd', 'lives'),
    mc('We ___ our grandparents last weekend.', 'visited', 'visit', 'visits', 'visiting'),
    mc('I didn’t ___ TV yesterday.', 'watch', 'watched', 'watches', 'watching'),
    mc('___ you study for the test?', 'Did', 'Were', 'Do', 'Was'),
  ),
  focus('Simple past: irregular verbs',
    mc('have → past simple', 'had', 'haved', 'has', 'hadded'),
    mc('get → past simple', 'got', 'getted', 'gets', 'gotted'),
    mc('buy → past simple', 'bought', 'buyed', 'brought', 'buys'),
    mc('Last night I ___ a strange dream.', 'had', 'have', 'haved', 'has'),
    mc('She ___ home at 10 p.m.', 'got', 'get', 'getted', 'gots'),
    mc('What ___ you do yesterday?', 'did', 'were', 'do', 'was'),
  ),
]

/* ───────────── Elemental I ───────────── */

const ELEMENTAL1_EA1 = [
  focus('Verb be',
    mc('My sister ___ a nurse.', 'is', 'are', 'am', 'be'),
    mc('We ___ from Peru.', 'are', 'is', 'am', 'be'),
    mc('I ___ hungry. I just ate.', '’m not', 'isn’t', 'aren’t', 'not'),
    mc('___ they your friends?', 'Are', 'Is', 'Do', 'Am'),
    mc('Is he a teacher? – No, he ___.', 'isn’t', 'aren’t', 'doesn’t', 'not'),
    mc('Choose the correct question.', 'Where are you from?', 'Where you are from?', 'Where is you from?', 'From where you are?'),
  ),
  focus('Possessive adjectives',
    mc('I love ___ job.', 'my', 'me', 'I', 'mine'),
    mc('Anna and ___ husband live in Rome.', 'her', 'his', 'she', 'hers'),
    mc('They sold ___ car.', 'their', 'there', 'they', 'them'),
    mc('The company changed ___ name.', 'its', 'it’s', 'it', 'its’'),
    mc('We love ___ new teacher.', 'our', 'us', 'we', 'ours'),
    mc('What’s ___ name? – I’m Carlos.', 'your', 'you', 'you’re', 'yours'),
  ),
  focus('A / an & plurals',
    mc('I have ___ orange and ___ banana.', 'an / a', 'a / an', 'a / a', 'an / an'),
    mc('one box, two ___', 'boxes', 'boxs', 'boxies', 'box'),
    mc('one woman, two ___', 'women', 'womans', 'womens', 'woman'),
    mc('one city, two ___', 'cities', 'citys', 'cityes', 'city'),
    mc('Choose the correct sentence.', 'It’s an old car.', 'It’s a old car.', 'It’s old a car.', 'It’s an old cars.'),
    mc('one knife, two ___', 'knives', 'knifes', 'knifs', 'knife'),
  ),
  focus('Simple present',
    mc('He ___ in a hospital.', 'works', 'work', 'working', 'is work'),
    mc('They ___ like fish.', 'don’t', 'doesn’t', 'aren’t', 'not'),
    mc('___ your brother play football?', 'Does', 'Do', 'Is', 'Are'),
    mc('My mother ___ TV every night.', 'watches', 'watchs', 'watch', 'watching'),
    mc('Does she speak English? – Yes, she ___.', 'does', 'do', 'is', 'speaks'),
    mc('study → he ___', 'studies', 'studys', 'studyes', 'study'),
  ),
  focus('Question words',
    mc('___ do you live? – In Lima.', 'Where', 'When', 'What', 'Who'),
    mc('___ do you get up? – At 7 o’clock.', 'What time', 'Where', 'Who', 'How'),
    mc('___ is your teacher? – Mr. Brown.', 'Who', 'What', 'Where', 'How'),
    mc('___ do you go to work? – By bus.', 'How', 'What', 'Where', 'Why'),
    mc('Choose the correct question.', 'What time does the class start?', 'What time the class starts?', 'What time does start the class?', 'What time does the class starts?'),
    mc('___ do you like coffee? – Because it’s delicious.', 'Why', 'What', 'How', 'Where'),
  ),
]

const ELEMENTAL1_EA2 = [
  focus('Prepositions of time and place',
    mc('I was born ___ 1998.', 'in', 'on', 'at', 'to'),
    mc('The party is ___ Saturday.', 'on', 'in', 'at', 'to'),
    mc('I go to bed ___ 11 o’clock.', 'at', 'in', 'on', 'to'),
    mc('We go skiing ___ winter.', 'in', 'on', 'at', 'to'),
    mc('She’s ___ work right now.', 'at', 'in', 'on', 'to'),
    mc('I have lunch ___ noon.', 'at', 'in', 'on', 'to'),
  ),
  focus('Daily routine + in / on / at / to',
    mc('My dad ___ a shower ___ the morning.', 'takes / in', 'does / in', 'takes / on', 'makes / at'),
    mc('Diego goes ___ bed ___ midnight.', 'to / at', 'in / at', 'to / on', 'at / in'),
    mc('Choose the correct sentence.', 'He goes home early on Fridays.', 'He goes to home early on Fridays.', 'He goes home early in Fridays.', 'He goes to home early at Fridays.'),
    mc('Sofía and Martín ___ the housework ___ the weekend.', 'do / on', 'make / on', 'do / in', 'make / at'),
    mc('I usually get ___ work at 8:45.', 'to', 'at', 'in', 'on'),
    mc('We have lunch ___ work ___ 1:30.', 'at / at', 'in / at', 'to / on', 'at / in'),
    mc('Choose the correct sentence.', 'She gets home late at night.', 'She gets to home late at night.', 'She gets home late in night.', 'She gets at home late at night.'),
    mc('My grandma ___ the dog for a walk ___ the evening.', 'takes / in', 'does / in', 'takes / at', 'makes / on'),
    mc('Emma ___ to Spanish classes ___ Tuesdays.', 'goes / on', 'goes / in', 'takes / at', 'does / on'),
    mc('Andrés ___ his emails ___ 9:00.', 'checks / at', 'checks / in', 'does / on', 'makes / at'),
  ),
  focus('Adverbs of frequency',
    mc('Choose the correct sentence.', 'I usually get up at 7.', 'I get up usually at 7.', 'I get usually up at 7.', 'I usually am get up at 7.'),
    mc('Choose the correct sentence.', 'He is always tired.', 'He always tired is.', 'Always is he tired.', 'He tired is always.'),
    mc('I go swimming once ___ week.', 'a', 'the', 'in', 'on'),
    mc('Which one means “almost never”?', 'hardly ever', 'usually', 'always', 'often'),
    mc('How ___ do you go to the gym? – Twice a week.', 'often', 'much', 'many', 'long'),
    mc('Choose the correct sentence.', 'We never eat meat.', 'We eat never meat.', 'We don’t never eat meat.', 'Never we eat meat.'),
  ),
  focus('Present continuous or simple?',
    mc('Look! It ___.', '’s snowing', 'snows', 'snow', 'snowing'),
    mc('It ___ a lot in April.', 'rains', 'is raining', 'rain', 'raining'),
    mc('What ___ you usually do on weekends?', 'do', 'are', 'does', 'is'),
    mc('Why ___ you laughing?', 'are', 'do', 'is', 'does'),
    mc('I ___ jeans to work, but today I ___ a dress.', 'usually wear / ’m wearing', '’m usually wearing / wear', 'usually wear / wear', '’m wearing / ’m wearing'),
    mc('Shh! I ___ to the radio.', '’m listening', 'listen', 'listens', 'listening'),
  ),
  focus('Like + -ing',
    mc('I love ___ in the mountains.', 'walking', 'walk', 'walks', 'to walking'),
    mc('My sister hates ___ the dishes.', 'doing', 'do', 'does', 'to doing'),
    mc('Do you like ___ photos?', 'taking', 'take', 'takes', 'to taking'),
    mc('swim → -ing', 'swimming', 'swiming', 'swimeing', 'swims'),
    mc('We don’t like ___ late.', 'working', 'work', 'works', 'to working'),
    mc('Choose the correct sentence.', 'She likes reading.', 'She likes read.', 'She like reading.', 'She likes to reading.'),
  ),
]

/* ───────────── Intermedio I ───────────── */

const INTERMEDIO1_EA1 = [
  focus('Word order in questions',
    mc('Choose the correct question.', 'Where did you go last summer?', 'Where you went last summer?', 'Where did you went last summer?', 'Where went you last summer?'),
    mc('Choose the correct question.', 'What are you going to do tonight?', 'What you are going to do tonight?', 'What are you going do tonight?', 'What do you going to do tonight?'),
    mc('What kind of music ___ you like?', 'do', 'are', 'does', 'is'),
    mc('Choose the correct question.', 'Who do you live with?', 'Who you live with?', 'With who you live?', 'Who does you live with?'),
    mc('Where ___ your parents from?', 'are', 'do', 'is', 'does'),
    mc('Choose the correct question.', 'What does your brother do?', 'What your brother does?', 'What does your brother does?', 'What do your brother do?'),
  ),
  focus('Simple past',
    mc('We ___ to Brazil on vacation.', 'went', 'goed', 'gone', 'go'),
    mc('They ___ a great hotel near the beach.', 'found', 'finded', 'find', 'founded'),
    mc('I didn’t ___ any photos.', 'take', 'took', 'taken', 'takes'),
    mc('stay → past simple', 'stayed', 'staid', 'stood', 'stayd'),
    mc('___ it rain during your trip?', 'Did', 'Was', 'Were', 'Does'),
    mc('The flight ___ three hours late.', 'arrived', 'arrive', 'arrives', 'arriven'),
  ),
  focus('Prepositions of time and place',
    mc('I’ll see you ___ the weekend.', 'on', 'in', 'to', 'for'),
    mc('The accident happened ___ 5:30 p.m.', 'at', 'in', 'on', 'to'),
    mc('Man landed on the moon ___ 1969.', 'in', 'on', 'at', 'since'),
    mc('The keys are ___ my bag.', 'in', 'on', 'at', 'to'),
    mc('She lives ___ the third floor.', 'on', 'in', 'at', 'to'),
    mc('I was born ___ May 3rd.', 'on', 'in', 'at', 'to'),
  ),
  focus('Going to & present continuous (future)',
    mc('Look at that car! It ___ crash!', '’s going to', 'goes to', '’s crashing to', 'going to'),
    mc('I ___ my dentist at 4 tomorrow. It’s in my calendar.', '’m seeing', 'see', 'saw', '’m see'),
    mc('We ___ buy a new car next year.', '’re going to', 'going to', '’re going', 'go to'),
    mc('What time ___ your flight leaving?', 'is', 'does', 'are', 'will'),
    mc('Choose the correct sentence.', 'I’m not going to work tomorrow.', 'I’m not going work tomorrow.', 'I don’t going to work tomorrow.', 'I not going to work tomorrow.'),
    mc('They ___ married in June. The invitations are ready.', '’re getting', 'get', 'got', '’re get'),
  ),
  focus('Verbs + prepositions',
    mc('I’m waiting ___ the bus.', 'for', 'to', 'at', 'on'),
    mc('She’s thinking ___ changing jobs.', 'about', 'in', 'on', 'to'),
    mc('Do you agree ___ me?', 'with', 'to', 'on', 'at'),
    mc('This bag belongs ___ Sara.', 'to', 'for', 'at', 'with'),
    mc('We talked ___ the movie for hours.', 'about', 'on', 'to', 'at'),
    mc('He always argues ___ his brother.', 'with', 'to', 'for', 'at'),
  ),
]

const INTERMEDIO1_EA2 = [
  focus('Present perfect: yet, already, just',
    mc('I haven’t finished ___.', 'yet', 'already', 'just', 'still'),
    mc('She’s ___ left. You missed her by one minute.', 'just', 'yet', 'ever', 'still'),
    mc('Have you ___ done your homework? Wow, that was fast!', 'already', 'yet', 'ever', 'still'),
    mc('They ___ bought the tickets. They’re in my bag.', '’ve already', '’ve yet', '’ve still', 'yet have'),
    mc('Choose the correct question.', 'Have you cleaned your room yet?', 'Have you cleaned yet your room?', 'Did you cleaned your room yet?', 'Have you clean your room yet?'),
    mc('see → past participle', 'seen', 'saw', 'seed', 'seeing'),
  ),
  focus('Present perfect or simple past?',
    mc('I ___ never been to Asia.', '’ve', 'did', 'was', '’m'),
    mc('We ___ to Mexico last year.', 'went', '’ve gone', '’ve been', 'go'),
    mc('___ you ever tried sushi?', 'Have', 'Did', 'Do', 'Are'),
    mc('When ___ you buy that jacket?', 'did', 'have', 'has', 'were'),
    mc('___ you ever ___ to Peru? – Yes, I went in 2019.', 'Have / been', 'Did / go', 'Have / went', 'Did / been'),
    mc('He ___ his first novel in 2010.', 'wrote', 'has written', 'writes', 'has wrote'),
  ),
  focus('-ed / -ing adjectives',
    mc('The trip was really ___.', 'tiring', 'tired', 'tire', 'tiredly'),
    mc('I’m very ___ in history.', 'interested', 'interesting', 'interest', 'interestingly'),
    mc('This book is so ___! Nothing happens.', 'boring', 'bored', 'bore', 'boredom'),
    mc('She was ___ when she saw the spider.', 'frightened', 'frightening', 'fright', 'frightens'),
    mc('The news was ___, and everyone was ___.', 'surprising / surprised', 'surprised / surprising', 'surprising / surprising', 'surprised / surprised'),
    mc('Are you ___? – Yes, a little. I’m going to bed.', 'tired', 'tiring', 'tire', 'tiredly'),
  ),
  focus('Comparatives & superlatives',
    mc('My brother is ___ than me.', 'taller', 'more tall', 'tallest', 'the taller'),
    mc('This test is ___ than the last one.', 'more difficult', 'difficulter', 'most difficult', 'more difficulter'),
    mc('She isn’t as tall ___ her sister.', 'as', 'than', 'that', 'like'),
    mc('It’s the ___ movie I’ve ever seen.', 'worst', 'baddest', 'worse', 'most bad'),
    mc('This is the most expensive hotel we’ve ever ___ in.', 'stayed', 'stay', 'stays', 'staying'),
    mc('good → comparative', 'better', 'gooder', 'more good', 'best'),
  ),
  focus('Will / won’t',
    mc('I think it ___ rain tomorrow. Take an umbrella.', 'will', 'is', 'does', 'going'),
    mc('Don’t worry, you ___ be late. It’s only 8 o’clock.', 'won’t', 'will', 'don’t', 'aren’t'),
    mc('Choose the correct question.', 'Will they win the game?', 'Will they wins the game?', 'Do they will win the game?', 'Will they to win the game?'),
    mc('She studied a lot. She’ll ___ the exam.', 'pass', 'passes', 'passing', 'to pass'),
    mc('will not = ___', 'won’t', 'willn’t', 'wont', 'don’t'),
    mc('The opposite of “remember” is ___.', 'forget', 'lose', 'miss', 'leave'),
  ),
]

/* ───────────── Intermedio Intensivo ───────────── */

const MAKE_OR_DO = focus('Make or do?',
  mc('Can you ___ me a favor?', 'do', 'make', 'have', 'take'),
  mc('I need to ___ a phone call.', 'make', 'do', 'say', 'tell'),
  mc('Don’t ___ so much noise!', 'make', 'do', 'have', 'give'),
  mc('Have you ___ your homework?', 'done', 'made', 'had', 'taken'),
  mc('Every morning I ___ the bed and ___ the ironing.', 'make / do', 'do / make', 'make / make', 'do / do'),
  mc('She ___ a lot of mistakes in the test.', 'made', 'did', 'had', 'took'),
)

const INTERMEDIO_INT_EA2 = [
  focus('Gerunds & infinitives',
    // Solo verbo + verbo. Like / love / hate también aceptan "to" en inglés
    // americano: por eso love y hate no llevan "to + verbo" como distractor.
    // Orden irregular a propósito: sin alternar infinitivo / gerundio, para que
    // jugado "en orden" no se adivine por patrón.
    mc('I want ___ a new phone.', 'to buy', 'buying', 'buy', 'bought'),
    mc('You need ___ more water.', 'to drink', 'drinking', 'drink', 'drank'),
    mc('Carmen enjoys ___ in the rain.', 'walking', 'to walk', 'walk', 'walked'),
    mc('I’d like ___ Japan one day.', 'to visit', 'visiting', 'visit', 'visited'),
    mc('Have you finished ___ the book?', 'reading', 'to read', 'read', 'reads'),
    mc('Do you mind ___ the window?', 'opening', 'to open', 'open', 'opened'),
    mc('Laura decided ___ her job last month.', 'to leave', 'leaving', 'leave', 'left'),
    mc('Kevin spends hours ___ video games.', 'playing', 'to play', 'play', 'played'),
    mc('We hope ___ you soon.', 'to see', 'seeing', 'see', 'saw'),
    mc('Don’t forget ___ the door!', 'to lock', 'locking', 'lock', 'locked'),
    mc('My grandma loves ___ cakes for the family.', 'baking', 'bake', 'baked', 'bakes'),
    mc('I don’t feel like ___ tonight.', 'cooking', 'to cook', 'cook', 'cooked'),
    mc('My son is learning ___.', 'to swim', 'swimming', 'swim', 'swam'),
    mc('Lucas hates ___ up early.', 'getting', 'get', 'got', 'gets'),
    mc('Tom promised ___ me with my homework.', 'to help', 'helping', 'help', 'helped'),
  ),
  focus('First conditional',
    mc('If you study, you ___ the exam.', '’ll pass', 'would pass', 'passed', 'passing'),
    mc('If it ___ tomorrow, we won’t go to the beach.', 'rains', 'will rain', 'rained', 'would rain'),
    mc('If she ___ the bus, she ___ late.', 'misses / ’ll be', 'will miss / is', 'missed / ’ll be', 'misses / would be'),
    mc('What will you do if you ___ the job?', 'don’t get', 'won’t get', 'didn’t get', 'not get'),
    mc('I ___ call you if I have time.', '’ll', 'would', 'am', 'did'),
    mc('Choose the correct sentence.', 'If I see him, I’ll tell him.', 'If I will see him, I’ll tell him.', 'If I see him, I tell him will.', 'If I saw him, I’ll tell him.'),
  ),
  focus('Second conditional',
    mc('If I ___ rich, I’d travel the world.', 'were', 'am', 'will be', 'would be'),
    mc('If she had a car, she ___ drive to work.', 'would', 'will', 'does', 'did'),
    mc('What would you do if you ___ a million dollars?', 'won', 'win', 'will win', 'would win'),
    mc('If we ___ more time, we ___ visit you.', 'had / would', 'have / would', 'had / will', 'would have / would'),
    mc('If I were you, I ___ take that job.', 'would', 'will', 'am', 'did'),
    mc('Choose the correct sentence.', 'If I lived near the beach, I’d go swimming every day.', 'If I would live near the beach, I’d go swimming every day.', 'If I lived near the beach, I go swimming every day.', 'If I live near the beach, I’d go swimming every day.'),
  ),
  focus('Present perfect + for / since',
    mc('I’ve known her ___ 2010.', 'since', 'for', 'from', 'ago'),
    mc('They’ve been married ___ twenty years.', 'for', 'since', 'during', 'ago'),
    mc('How long ___ you lived here?', 'have', 'did', 'are', 'do'),
    mc('She has worked here ___ she finished college.', 'since', 'for', 'when', 'ago'),
    mc('We ___ this car for five years, and it still works great.', '’ve had', 'have', '’re having', '’ve have'),
    mc('___ last Monday', 'since', 'for', 'during'),
  ),
  focus('Used to',
    mc('I ___ have long hair when I was a kid.', 'used to', 'use to', 'was used to', 'used'),
    mc('Did you ___ play video games?', 'use to', 'used to', 'using to', 'uses to'),
    mc('We didn’t ___ go on vacation much.', 'use to', 'used to', 'using', 'uses to'),
    mc('My grandmother used to ___ bread every Sunday.', 'make', 'made', 'making', 'makes'),
    mc('Choose the correct sentence.', 'He used to live in Chile.', 'He use to live in Chile.', 'He used to lived in Chile.', 'He was used to live in Chile.'),
    mc('There ___ be a cinema here, but now it’s a bank.', 'used to', 'use to', 'was', 'did use'),
  ),
  focus('Phrasal verbs',
    mc('Start doing a new hobby:', 'take up', 'give up', 'look after', 'turn down'),
    mc('Take care of a child or a pet:', 'look after', 'look for', 'look up', 'look at'),
    mc('Try to find something you lost:', 'look for', 'look after', 'look up', 'find out'),
    mc('Choose the correct sentence.', 'Can you pick them up at 5?', 'Can you pick up them at 5?', 'Can you them pick up at 5?', 'Can you pick them at 5 up?'),
    mc('Choose the correct sentence.', 'I’ll look it up in the dictionary.', 'I’ll look up it in the dictionary.', 'I’ll it look up in the dictionary.', 'I’ll look it in the dictionary up.'),
    mc('put on (clothes) ↔ take ___', 'off', 'out', 'up', 'down'),
  ),
  focus('Should & might',
    mc('You ___ see a doctor. You look sick.', 'should', 'should to', 'shoulds', 'would to'),
    mc('You ___ eat so much sugar. It’s bad for you.', 'shouldn’t', 'don’t should', 'should not to', 'aren’t should'),
    mc('I ___ go to the party. I’m not sure yet.', 'might', 'might to', 'mights', 'am might'),
    mc('Take a coat. It ___ be cold tonight.', 'might', 'might to', 'mights', 'is might'),
    mc('___ I call her? – Yes, you should.', 'Should', 'Do', 'Am', 'Does'),
    mc('Choose the correct sentence.', 'She might not come to class today.', 'She might not to come to class today.', 'She doesn’t might come to class today.', 'She mights not come to class today.'),
  ),
  focus('Past perfect',
    mc('When I got home, my family ___ dinner.', 'had already eaten', 'has already eaten', 'had already ate', 'already has eaten'),
    mc('She was tired because she ___ well.', 'hadn’t slept', 'hasn’t slept', 'didn’t slept', 'hadn’t sleep'),
    mc('I ___ never seen snow before I went to Canada.', 'had', 'have', 'was', 'did'),
    mc('go → past participle', 'gone', 'went', 'goed', 'going'),
    mc('When we ___ at the station, the train ___.', 'arrived / had left', 'had arrived / left', 'arrived / has left', 'arrive / had left'),
    mc('Choose the correct question.', 'Had you met him before?', 'Did you had met him before?', 'Had you meet him before?', 'Have you met him before yesterday?'),
  ),
]

/* curso → [EA1, EA2] */
export const FOCUS = {
  basico2: [BASICO2_EA1, BASICO2_EA2],
  elemental1: [ELEMENTAL1_EA1, ELEMENTAL1_EA2],
  intermedio1: [INTERMEDIO1_EA1, INTERMEDIO1_EA2],
  // EA1 del intensivo = KC de Intermedio I completo, más "make or do", que ahí es KC.
  intermedioInt: [[...INTERMEDIO1_EA1, ...INTERMEDIO1_EA2, MAKE_OR_DO], INTERMEDIO_INT_EA2],
}
