/* Sets de preguntas por nivel.

   Cada pregunta:
     prompt      la pregunta tal como se proyecta
     subject     accept: sujetos válidos de la RESPUESTA (ojo: "you" → "I")
                 distractors: trampas típicas (la wh-word, el complemento, el pronombre equivocado)
     verb        accept: el verbo de la respuesta con su carga temporal
                 ("did … work" → "worked": el auxiliar se lleva el tiempo y al responder vuelve al verbo)
     wh          clave de WH_TYPES (logic.js): qué tipo de dato pide la pregunta
     example     una respuesta modelo posible, para mostrar al revelar */
export const SETS = [
  {
    id: 'a1',
    name: 'A1 · Starter',
    topics: 'Present simple · Past simple (regular)',
    questions: [
      { prompt: 'Where did María work yesterday?', wh: 'place', example: 'She worked at the hospital.',
        subject: { accept: ['María', 'She'], distractors: ['He', 'Yesterday', 'They'] },
        verb: { accept: ['worked'], distractors: ['work', 'works', 'did work'] } },
      { prompt: 'Where does Tom live?', wh: 'place', example: 'He lives in London.',
        subject: { accept: ['Tom', 'He'], distractors: ['Where', 'It', 'They'] },
        verb: { accept: ['lives'], distractors: ['live', 'does live', 'living'] } },
      { prompt: 'What time do you get up?', wh: 'time', example: 'I get up at seven o’clock.',
        subject: { accept: ['I'], distractors: ['You', 'He', 'It'] },
        verb: { accept: ['get up'], distractors: ['gets up', 'got up', 'do get up'] } },
      { prompt: 'What does Anna eat for breakfast?', wh: 'thing', example: 'She eats toast and eggs.',
        subject: { accept: ['Anna', 'She'], distractors: ['Breakfast', 'He', 'It'] },
        verb: { accept: ['eats'], distractors: ['eat', 'does eat', 'eating'] } },
      { prompt: 'How do your parents go to work?', wh: 'manner', example: 'They go to work by bus.',
        subject: { accept: ['My parents', 'They'], distractors: ['Your parents', 'We', 'He'] },
        verb: { accept: ['go'], distractors: ['goes', 'went', 'do go'] } },
      { prompt: 'Why do Sam and Lucy study English?', wh: 'reason', example: 'They study English because they want to travel.',
        subject: { accept: ['Sam and Lucy', 'They'], distractors: ['She', 'We', 'English'] },
        verb: { accept: ['study'], distractors: ['studies', 'studied', 'do study'] } },
      { prompt: 'When did your brother visit Paris?', wh: 'time', example: 'He visited Paris last summer.',
        subject: { accept: ['My brother', 'He'], distractors: ['Your brother', 'Paris', 'She'] },
        verb: { accept: ['visited'], distractors: ['visit', 'visits', 'did visit'] } },
      { prompt: 'How many cats does Peter have?', wh: 'quantity', example: 'He has three cats.',
        subject: { accept: ['Peter', 'He'], distractors: ['Cats', 'They', 'She'] },
        verb: { accept: ['has'], distractors: ['have', 'does have', 'haves'] } },
      { prompt: 'How often does Laura play tennis?', wh: 'frequency', example: 'She plays tennis twice a week.',
        subject: { accept: ['Laura', 'She'], distractors: ['Tennis', 'He', 'It'] },
        verb: { accept: ['plays'], distractors: ['play', 'played', 'does play'] } },
    ],
  },
  {
    id: 'a2',
    name: 'A2 · Elementary',
    topics: 'Past simple (irregular) · Continuous · will',
    questions: [
      { prompt: 'Where did you go last weekend?', wh: 'place', example: 'I went to the beach.',
        subject: { accept: ['I', 'We'], distractors: ['You', 'He', 'They'] },
        verb: { accept: ['went'], distractors: ['go', 'goed', 'did go'] } },
      { prompt: 'What did Tom buy at the supermarket?', wh: 'thing', example: 'He bought some bread and milk.',
        subject: { accept: ['Tom', 'He'], distractors: ['The supermarket', 'She', 'It'] },
        verb: { accept: ['bought'], distractors: ['buy', 'buyed', 'did buy'] } },
      { prompt: 'What is Ana doing right now?', wh: 'action', example: 'She is reading a book.',
        subject: { accept: ['Ana', 'She'], distractors: ['He', 'It', 'Now'] },
        verb: { accept: ['is doing'], distractors: ['does', 'doing', 'is do'] } },
      { prompt: 'Why were the students late?', wh: 'reason', example: 'They were late because the bus broke down.',
        subject: { accept: ['The students', 'They'], distractors: ['He', 'We', 'Late'] },
        verb: { accept: ['were'], distractors: ['was', 'are', 'were being'] } },
      { prompt: 'Who did Carlos meet at the party?', wh: 'person', example: 'He met his old teacher.',
        subject: { accept: ['Carlos', 'He'], distractors: ['The party', 'She', 'They'] },
        verb: { accept: ['met'], distractors: ['meet', 'meeted', 'did meet'] } },
      { prompt: 'How long did the film last?', wh: 'duration', example: 'It lasted two hours.',
        subject: { accept: ['The film', 'It'], distractors: ['He', 'They', 'Long'] },
        verb: { accept: ['lasted'], distractors: ['last', 'lasts', 'did last'] } },
      { prompt: 'When will your cousins arrive?', wh: 'time', example: 'They will arrive on Friday.',
        subject: { accept: ['My cousins', 'They'], distractors: ['Your cousins', 'He', 'We'] },
        verb: { accept: ['will arrive'], distractors: ['arrive', 'arrived', 'will arrived'] } },
      { prompt: 'How did Mike break his arm?', wh: 'manner', example: 'He broke it playing football.',
        subject: { accept: ['Mike', 'He'], distractors: ['His arm', 'She', 'It'] },
        verb: { accept: ['broke'], distractors: ['break', 'broken', 'breaked'] } },
      { prompt: 'What were the children watching?', wh: 'thing', example: 'They were watching a cartoon.',
        subject: { accept: ['The children', 'They'], distractors: ['He', 'It', 'We'] },
        verb: { accept: ['were watching'], distractors: ['watched', 'was watching', 'were watch'] } },
    ],
  },
  {
    id: 'b1',
    name: 'B1 · Intermediate',
    topics: 'Present perfect · going to · Modals · Passive',
    questions: [
      { prompt: 'How long have you lived in this city?', wh: 'duration', example: 'I have lived here for five years.',
        subject: { accept: ['I', 'We'], distractors: ['You', 'This city', 'He'] },
        verb: { accept: ['have lived'], distractors: ['lived', 'has lived', 'have live'] } },
      { prompt: 'What has Emma just finished?', wh: 'thing', example: 'She has just finished her homework.',
        subject: { accept: ['Emma', 'She'], distractors: ['He', 'It', 'They'] },
        verb: { accept: ['has finished'], distractors: ['have finished', 'finished', 'has finish'] } },
      { prompt: 'Where are they going to spend their holidays?', wh: 'place', example: 'They are going to spend them in the south.',
        subject: { accept: ['They'], distractors: ['Their holidays', 'We', 'He'] },
        verb: { accept: ['are going to spend'], distractors: ['spend', 'are going spend', 'are going to spent'] } },
      { prompt: 'Why had the train left so early?', wh: 'reason', example: 'It had left early because of the storm.',
        subject: { accept: ['The train', 'It'], distractors: ['He', 'They', 'Early'] },
        verb: { accept: ['had left'], distractors: ['has left', 'left', 'had leave'] } },
      { prompt: 'How much money would you need?', wh: 'quantity', example: 'I would need about 200 dollars.',
        subject: { accept: ['I', 'We'], distractors: ['You', 'Money', 'It'] },
        verb: { accept: ['would need'], distractors: ['will need', 'need', 'would needed'] } },
      { prompt: 'Who should Jake call for help?', wh: 'person', example: 'He should call his older sister.',
        subject: { accept: ['Jake', 'He'], distractors: ['Help', 'She', 'They'] },
        verb: { accept: ['should call'], distractors: ['should to call', 'calls', 'should called'] } },
      { prompt: 'When was the bridge built?', wh: 'time', example: 'It was built in 1920.',
        subject: { accept: ['The bridge', 'It'], distractors: ['He', 'They', 'Built'] },
        verb: { accept: ['was built'], distractors: ['built', 'is built', 'was build'] } },
      { prompt: 'How many books has Ben read this year?', wh: 'quantity', example: 'He has read twelve books.',
        subject: { accept: ['Ben', 'He'], distractors: ['Books', 'They', 'She'] },
        verb: { accept: ['has read'], distractors: ['have read', 'readed', 'has red'] } },
    ],
  },
]

export const getSet = (id) => SETS.find((s) => s.id === id) ?? SETS[0]
